# Generated by Django 6.0.6 on 2026-07-03 07:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('leads', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Curriculum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('level', models.CharField(blank=True, choices=[('Absolute beginner', 'Absolute beginner'), ('N5', 'N5'), ('N4', 'N4'), ('N3', 'N3'), ('N2', 'N2'), ('N1', 'N1'), ('None', 'None')], max_length=30)),
                ('description', models.TextField(blank=True)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Cohort',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('custom_data', models.JSONField(blank=True, default=dict)),
                ('code', models.CharField(help_text='e.g. C1', max_length=20, unique=True, verbose_name='Cohort ID')),
                ('name', models.CharField(blank=True, help_text='Auto pattern e.g. C1-260630-SB-19', max_length=80, verbose_name='Cohort Name')),
                ('level', models.CharField(blank=True, choices=[('Absolute beginner', 'Absolute beginner'), ('N5', 'N5'), ('N4', 'N4'), ('N3', 'N3'), ('N2', 'N2'), ('N1', 'N1'), ('None', 'None')], max_length=30)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('class_time', models.TimeField(blank=True, null=True)),
                ('whatsapp_group_link', models.URLField(blank=True)),
                ('status', models.CharField(choices=[('Upcoming', 'Upcoming'), ('Started', 'Started'), ('On Hold', 'On Hold'), ('Finished', 'Finished')], default='Upcoming', max_length=20)),
                ('total_weeks', models.PositiveSmallIntegerField(default=12, help_text='Curriculum length for this cohort — 6 class days per week.')),
                ('assigned_teacher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cohorts_taught', to=settings.AUTH_USER_MODEL)),
                ('curriculum', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cohorts', to='cohorts.curriculum')),
            ],
            options={
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='CurriculumChapter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_number', models.PositiveSmallIntegerField(default=1)),
                ('day_number', models.PositiveSmallIntegerField()),
                ('title', models.CharField(max_length=200, verbose_name='Chapter / Lesson')),
                ('notes', models.TextField(blank=True)),
                ('assigned_teacher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='curriculum_chapters', to=settings.AUTH_USER_MODEL)),
                ('curriculum', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chapters', to='cohorts.curriculum')),
            ],
            options={
                'ordering': ['curriculum', 'week_number', 'day_number'],
                'unique_together': {('curriculum', 'day_number')},
            },
        ),
        migrations.CreateModel(
            name='ClassEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('class', 'Class'), ('event', 'Event')], default='class', max_length=10)),
                ('date', models.DateField(blank=True, null=True)),
                ('time', models.TimeField(blank=True, null=True)),
                ('schedule_week', models.PositiveSmallIntegerField(blank=True, help_text='Optional — which week of the cohort this roughly corresponds to, for reference only.', null=True, verbose_name='Week (optional)')),
                ('schedule_day', models.PositiveSmallIntegerField(blank=True, help_text='Optional — which day of that week, for reference only.', null=True, verbose_name='Day (optional)')),
                ('joining_link', models.URLField(blank=True)),
                ('passcode', models.CharField(blank=True, help_text="Leave blank if there's no passcode.", max_length=50)),
                ('notice', models.TextField(blank=True, help_text='Optional — shown highlighted to students on the Student Portal.', verbose_name='Notice')),
                ('details', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True, help_text='Optional — internal notes, not shown to students.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='class_events_created', to=settings.AUTH_USER_MODEL)),
                ('cohort', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='cohorts.cohort')),
                ('related_chapter', models.ForeignKey(blank=True, help_text="Optional — tag this event to a curriculum chapter, for reference only. Doesn't affect Daily Scoring.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='class_events', to='cohorts.curriculumchapter')),
            ],
            options={
                'ordering': ['date', 'time'],
            },
        ),
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('custom_data', models.JSONField(blank=True, default=dict)),
                ('enrolled_date', models.DateField(blank=True, null=True)),
                ('followup_needed', models.BooleanField(default=False)),
                ('followup_outcome', models.TextField(blank=True)),
                ('remarks', models.TextField(blank=True)),
                ('ready_for_next_week', models.BooleanField(default=False, help_text='Manually confirmed once auto-eligible')),
                ('cohort', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='cohorts.cohort')),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='leads.lead')),
            ],
            options={
                'ordering': ['-enrolled_date'],
                'unique_together': {('lead', 'cohort')},
            },
        ),
        migrations.CreateModel(
            name='Followup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('custom_data', models.JSONField(blank=True, default=dict)),
                ('followup_type', models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('needs_attention', 'Needs Attention'), ('general', 'General')], default='general', max_length=20)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('remark', models.TextField(blank=True)),
                ('done', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='followups_created', to=settings.AUTH_USER_MODEL)),
                ('enrollment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='followups', to='cohorts.enrollment')),
                ('lead', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='followups', to='leads.lead')),
            ],
            options={
                'ordering': ['done', 'due_date'],
            },
        ),
        migrations.CreateModel(
            name='DailyScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('custom_data', models.JSONField(blank=True, default=dict)),
                ('day_number', models.PositiveSmallIntegerField()),
                ('date', models.DateField(blank=True, null=True)),
                ('lesson', models.CharField(blank=True, max_length=200)),
                ('status', models.CharField(blank=True, choices=[('Present', 'Present'), ('Absent', 'Absent')], max_length=10)),
                ('class_presence', models.PositiveSmallIntegerField(blank=True, choices=[(5, '5'), (4, '4'), (3, '3'), (2, '2'), (1, '1')], null=True)),
                ('effort_discipline', models.PositiveSmallIntegerField(blank=True, choices=[(5, '5'), (4, '4'), (3, '3'), (2, '2'), (1, '1')], null=True)),
                ('hw_practice', models.PositiveSmallIntegerField(blank=True, choices=[(5, '5'), (3, '3'), (1, '1'), (0, '0')], null=True)),
                ('note', models.CharField(blank=True, max_length=300)),
                ('needs_followup', models.BooleanField(default=False, verbose_name='Needs Followup?')),
                ('asked_documentation', models.CharField(blank=True, choices=[('none', 'None'), ('asked', 'Asked Documentation')], default='none', max_length=10)),
                ('scored_at', models.DateTimeField(auto_now=True)),
                ('scored_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scores_given', to=settings.AUTH_USER_MODEL)),
                ('enrollment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_scores', to='cohorts.enrollment')),
            ],
            options={
                'ordering': ['enrollment', 'day_number'],
                'unique_together': {('enrollment', 'day_number')},
            },
        ),
    ]
