# Generated by Django 6.0.6 on 2026-07-03 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FieldDefinition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_model', models.CharField(choices=[('lead', 'Lead'), ('consultation_slot', 'Consultation Slot'), ('consultation', 'Consultation'), ('post_consultation_call', 'Post Consultation Call'), ('cohort', 'Cohort'), ('enrollment', 'Enrollment'), ('daily_score', 'Daily Score'), ('followup', 'Follow-up')], max_length=30)),
                ('key', models.SlugField(help_text='Internal name, e.g. parent_contact', max_length=60)),
                ('label', models.CharField(max_length=120)),
                ('field_type', models.CharField(choices=[('text', 'Text'), ('textarea', 'Long text'), ('number', 'Number'), ('date', 'Date'), ('time', 'Time'), ('boolean', 'Yes/No'), ('dropdown', 'Dropdown'), ('multiselect', 'Checkboxes (multi)'), ('phone', 'Phone'), ('link', 'Link/URL')], default='text', max_length=20)),
                ('options', models.JSONField(blank=True, default=list, help_text='For dropdown/checkboxes: list of option strings')),
                ('group', models.CharField(blank=True, help_text='Section heading to show this field under', max_length=80)),
                ('order', models.PositiveIntegerField(default=0)),
                ('required', models.BooleanField(default=False)),
                ('show_on_dashboard_tally', models.BooleanField(default=False, help_text='Auto-tally this dropdown/checkbox field on the Dashboard')),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['target_model', 'order', 'id'],
                'unique_together': {('target_model', 'key')},
            },
        ),
    ]
