# Generated by Django 6.0.6 on 2026-07-03 07:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='IntakeTarget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('custom_data', models.JSONField(blank=True, default=dict)),
                ('user_code', models.CharField(max_length=30, unique=True, verbose_name='User ID')),
                ('full_name', models.CharField(max_length=150)),
                ('phone', models.CharField(max_length=30)),
                ('signup_date', models.DateField(blank=True, null=True)),
                ('why_learn_japanese', models.CharField(blank=True, choices=[('study', 'To Study in Japan (Student)'), ('work', 'To Work in Japan (Working or SSW)'), ('dependent_visa', 'Dependent Visa (Family Reunification)'), ('travel', 'Travel to Japan (Sightseeing)'), ('personal_interest', 'Personal Interest (Anime, Culture, Language)')], max_length=30, verbose_name='Why do you want to learn Japanese?')),
                ('journey_progress', models.CharField(blank=True, choices=[('self_study_starting', 'Just started learning by myself at home'), ('exploring_consultancy', 'Exploring consultancies'), ('just_joined_consultancy', 'Just joined a consultancy'), ('joined_not_satisfied', 'Joined a consultancy, but not satisfied'), ('joined_satisfied', 'Joined a consultancy and satisfied')], max_length=30, verbose_name='How far are you on learning Japanese?')),
                ('level', models.CharField(blank=True, choices=[('Absolute beginner', 'Absolute beginner'), ('N5', 'N5'), ('N4', 'N4'), ('N3', 'N3'), ('N2', 'N2'), ('N1', 'N1'), ('None', 'None')], max_length=30)),
                ('hiragana_katakana', models.CharField(blank=True, choices=[('None', 'None'), ('Hiragana only', 'Hiragana only'), ('Katakana only', 'Katakana only'), ('Both', 'Both'), ('Fluent', 'Fluent')], max_length=30, verbose_name='Hiragana & Katakana familiarity')),
                ('skill_focus', models.CharField(blank=True, choices=[('Vocab', 'Vocab'), ('Grammar', 'Grammar'), ('Kanji', 'Kanji'), ('Listening & Speaking', 'Listening & Speaking'), ('Exam Preparation', 'Exam Preparation')], max_length=20)),
                ('survey_language', models.CharField(blank=True, choices=[('NP', 'Nepali (NP)'), ('JP', 'Japanese (JP)'), ('EN', 'English (EN)')], max_length=5)),
                ('visa_category', models.CharField(blank=True, choices=[('SSW', 'SSW'), ('Student Visa', 'Student Visa'), ('Working Visa', 'Working Visa'), ('Dependent', 'Dependent'), ('Not Decided Yet', 'Not Decided Yet'), ('Visit Visa', 'Visit Visa'), ('TITP visa', 'TITP visa')], max_length=30)),
                ('already_in_consultancy', models.BooleanField(default=False)),
                ('planning_join_consultancy', models.BooleanField(default=False)),
                ('pain_fee', models.BooleanField(default=False, verbose_name='Fee Concern?')),
                ('pain_visa_rejection', models.BooleanField(default=False, verbose_name='Visa Rejected?')),
                ('pain_documentation', models.BooleanField(default=False, verbose_name='Document Submitted?')),
                ('documentation_concern', models.BooleanField(default=False, verbose_name='Documentation Concern?')),
                ('pain_accommodation', models.BooleanField(default=False, verbose_name='Accommodation Concern?')),
                ('pain_other', models.CharField(blank=True, max_length=200, verbose_name='Other concern')),
                ('topic_consultancy', models.BooleanField(default=False, verbose_name='Consultancy Doubts?')),
                ('topic_language_school', models.BooleanField(default=False, verbose_name='Language School Concerns?')),
                ('topic_jobs', models.BooleanField(default=False, verbose_name='Job Concern?')),
                ('topic_other', models.CharField(blank=True, max_length=200, verbose_name='Other topic')),
                ('curiosity_level', models.CharField(blank=True, choices=[('High', 'High'), ('Medium', 'Medium'), ('Low', 'Low'), ('None', 'None')], max_length=10, verbose_name='Curiosity to Know')),
                ('curiosity_note', models.CharField(blank=True, max_length=300, verbose_name='Curiosity Note')),
                ('call_date', models.DateField(blank=True, null=True, verbose_name='Call Date')),
                ('call_status', models.CharField(blank=True, choices=[('Scheduled', 'Scheduled'), ('Follow-up Needed', 'Follow-up Needed'), ('Not Interested', 'Not Interested'), ('No Answer', 'No Answer'), ('Completed', 'Completed'), ('Rescheduled', 'Rescheduled')], max_length=20)),
                ('preferred_call_language', models.CharField(blank=True, choices=[('Nepali', 'Nepali'), ('English', 'English')], max_length=10)),
                ('call_duration_seconds', models.PositiveIntegerField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('ready_for_consultation', models.BooleanField(default=False, verbose_name='Ready for Consultation?')),
                ('visa_interest', models.BooleanField(default=False, verbose_name='Interested in Visa Application (through us)?')),
                ('documentation_status', models.CharField(blank=True, choices=[('asked_in_class', 'Asked in Class (Next Followup Call)'), ('ready', 'Ready for Documentation'), ('received', 'Documentation Received Successfully')], max_length=20, verbose_name='Documentation Process')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('agent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leads_handled', to=settings.AUTH_USER_MODEL)),
                ('intake_target', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leads', to='leads.intaketarget')),
                ('student_account', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lead_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
