# Generated by Django 6.0.6 on 2026-07-03 07:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cohorts', '0001_initial'),
        ('leads', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConsultationSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True, null=True)),
                ('time', models.TimeField(blank=True, null=True)),
                ('meeting_link', models.URLField(blank=True, verbose_name='Link for Call')),
                ('status', models.CharField(choices=[('Open', 'Open'), ('Reserved', 'Reserved'), ('Completed', 'Completed'), ('Cancelled', 'Cancelled')], default='Open', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('counselor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='consultation_slots_run', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date', '-time'],
            },
        ),
        migrations.CreateModel(
            name='PostConsultationCall',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('custom_data', models.JSONField(blank=True, default=dict)),
                ('call_date', models.DateField(blank=True, null=True)),
                ('call_status', models.CharField(blank=True, choices=[('Scheduled', 'Scheduled'), ('Follow-up Needed', 'Follow-up Needed'), ('Not Interested', 'Not Interested'), ('No Answer', 'No Answer'), ('Completed', 'Completed'), ('Rescheduled', 'Rescheduled')], max_length=20)),
                ('consultation_feedback', models.TextField(blank=True, verbose_name='Consultation Feedback')),
                ('cohort_interest', models.BooleanField(default=False, verbose_name='Interested in Joining a Cohort?')),
                ('preferred_time', models.TimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('next_followup_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('called_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='post_consultation_calls_made', to=settings.AUTH_USER_MODEL)),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post_consultation_calls', to='leads.lead')),
                ('preferred_cohort', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='post_call_preferences', to='cohorts.cohort')),
            ],
            options={
                'ordering': ['-call_date'],
            },
        ),
        migrations.CreateModel(
            name='Consultation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('custom_data', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('Reserved', 'Reserved'), ('Completed', 'Completed'), ('No Show', 'No Show'), ('Cancelled', 'Cancelled')], default='Reserved', max_length=20)),
                ('user_seriousness', models.CharField(blank=True, choices=[('High', 'High'), ('Medium', 'Medium'), ('Low', 'Low'), ('Not Suitable', 'Not Suitable')], max_length=20)),
                ('main_concern', models.TextField(blank=True)),
                ('class_interest', models.BooleanField(default=False)),
                ('preferred_class_time', models.TimeField(blank=True, null=True)),
                ('preferred_class_start_date', models.DateField(blank=True, null=True)),
                ('pmf_score', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='PMF Score (1-5)')),
                ('note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consultations', to='leads.lead')),
                ('recommended_cohort', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recommended_for', to='cohorts.cohort')),
                ('slot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendees', to='consultations.consultationslot')),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('slot', 'lead')},
            },
        ),
    ]
